# .github/workflows/test.yml
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      # Docker is already available in GitHub Actions Ubuntu runners
      # Just verify it's running
      - name: Verify Docker
        run: docker --version

      - name: Start Supabase
        run: |
          npx supabase start
          sleep 10 # Give some time for services to be ready

      - name: Run Tests
        run: npm run test:coverage
        env:
          CI: true

      # Optional: Upload test results as artifacts
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage/